### ISSUE TITLE
Limit Order Bad Request

### ISSUE THREAD

**Issue by Schariss** [Petersoj/alpaca-java#90] opened 2021-03-07 22:12 UTC
```
Order limitOrderTSLA = alpacaAPI.requestNewLimitOrder(
		            "TSLA",
		            100,
		            OrderSide.BUY,
		            OrderTimeInForce.DAY,
		            600.00,
		            false);
```

**- Exception :** net.jacobpeterson.alpaca.rest.exception.AlpacaAPIRequestException: Alpaca API Request Exception! : Status Code = 400, Status Text = "Bad Request", API Response Code = 40010000, API Response Message = "request body format is invalid"
	at net.jacobpeterson.alpaca.AlpacaAPI.requestNewOrder(AlpacaAPI.java:500)

**Comment by Petersoj** [comment] 2021-03-07 22:21
What version are you using? That exact code is working for me on version `7.0`.
What Logger implementation are you using? Can you show me what the debug log outputs?

**Comment by Schariss** [comment] 2021-03-08 01:25
First of all, thank you for your fast response.
Yes, I am using version 7, and logger SLF4J library from Lombok on a spring
boot application.
I tried the requestNewOrder, requestNewMarketOrder and a few more methods,
they are all working fine with the exception of requestNewLimitOrder.

net.jacobpeterson.alpaca.rest.exception.AlpacaAPIRequestException: Alpaca
API Request Exception! : Status Code = 400, Status Text = "Bad Request",
API Response Code = 40010000, API Response Message = "request body format
is invalid"
at net.jacobpeterson.alpaca.AlpacaAPI.requestNewOrder(AlpacaAPI.java:503)
at
net.jacobpeterson.alpaca.AlpacaAPI.requestNewLimitOrder(AlpacaAPI.java:554)
at app.AlpacaApiTestApplication.run(AlpacaApiTestApplication.java:30)
at
org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:804)
at
org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:788)
at
org.springframework.boot.SpringApplication.run(SpringApplication.java:333)
at
org.springframework.boot.SpringApplication.run(SpringApplication.java:1311)
at
org.springframework.boot.SpringApplication.run(SpringApplication.java:1300)
at app.AlpacaApiTestApplication.main(AlpacaApiTestApplication.java:21)

Le dim. 7 mars 2021 à 23:21, Jacob Peterson <notifications@github.com> a
écrit :

**Comment by Petersoj** [comment] 2021-03-08 04:16
Could you try that code snippet on a fresh project just to ensure that the problem is isolated to your Spring boot application? It's still working fine for me.
Edit:
Also, could you set the log level of your logger implementation to `TRACE` before you instantiate the `AlpacaAPI` object. And then give me the output on the console (remove any sensitive information such as your API keys).

**Comment by Schariss** [comment] 2021-03-08 22:18
I tried the same code as yours again on a maven project, but the problem
persists.
The other methods are working fine, I even tried the requestNewOrder method
and specified the necessary fields for limit order but it didn't work.

net.jacobpeterson.alpaca.rest.exception.AlpacaAPIRequestException: Alpaca
API Request Exception! : Status Code = 400, Status Text = "Bad Request",
API Response Code = 40010000, API Response Message = "request body format
is invalid"

at net.jacobpeterson.alpaca.AlpacaAPI.requestNewOrder(AlpacaAPI.java:503)

at net.jacobpeterson.alpaca.AlpacaAPI.requestNewLimitOrder(
AlpacaAPI.java:554)

at com.adnane.alpaca_test.App.main(App.java:33)

Le lun. 8 mars 2021 à 05:16, Jacob Peterson <notifications@github.com> a
écrit :

**Comment by Petersoj** [comment] 2021-03-09 17:10
Is this Paper or Live?
Can you show me your `pom.xml`?
Could you also make a Zip archive of your maven project and upload it here?
Perhaps you could also re-download the artifact from Maven Central by deleting the `~/.m2/repository/net/jacobpeterson/alpaca-java/7.0` directory.

**Comment by Schariss** [comment] 2021-03-18 22:01
Paper.
**note** : I added the actuator dependency because the Realtime Market Data
method is not working, it does not generate an error but it displays the
following warning : failed to refresh live data from process xxxxx.
Here is my pom.xml file :

<parent>
<groupId>org.springframework.boot</groupId>
<artifactId>spring-boot-starter-parent</artifactId>
<version>2.4.3</version>
<relativePath/> 
</parent>
<groupId>com.adnane</groupId>
<artifactId>alpaca-api-test</artifactId>
<version>0.0.1-SNAPSHOT</version>
<name>alpaca-api-test</name>
<description>Demo project for Spring Boot</description>
<properties>
<java.version>1.8</java.version>
</properties>
<dependencies>
<dependency>
<groupId>org.springframework.boot</groupId>
<artifactId>spring-boot-starter-web</artifactId>
</dependency>
<dependency>
   <groupId>net.jacobpeterson</groupId>
   <artifactId>alpaca-java</artifactId>
   <version>7.0</version>
   <scope>compile</scope>
</dependency>
<dependency>
       <groupId>org.springframework.boot</groupId>
       <artifactId>spring-boot-starter-actuator</artifactId>
   </dependency>
   <dependency>
       <groupId>org.springframework.boot</groupId>
       <artifactId>spring-boot-devtools</artifactId>
       <optional>true</optional>
   </dependency>
<dependency>
<groupId>org.projectlombok</groupId>
<artifactId>lombok</artifactId>
<optional>true</optional>
</dependency>
<dependency>
<groupId>org.springframework.boot</groupId>
<artifactId>spring-boot-starter-test</artifactId>
<scope>test</scope>
</dependency>
</dependencies>

<build>
<plugins>
<plugin>
<groupId>org.springframework.boot</groupId>
<artifactId>spring-boot-maven-plugin</artifactId>
<configuration>
<excludes>
<exclude>
<groupId>org.projectlombok</groupId>
<artifactId>lombok</artifactId>
</exclude>
</excludes>
</configuration>
</plugin>
</plugins>
</build>

Le mar. 9 mars 2021 à 18:10, Jacob Peterson ***@***.***> a
écrit :

**Comment by Caceresenzo** [comment] 2021-04-26 20:47
Hi
I have the same problem, and i found what's causing it:

When you are doing a request with a limit price, you are sending:
```json
{
  "symbol": "AAPL",
  "side": "buy",
  "type": "limit",
  "time_in_force": "day",
  "qty": "1.0",
  "limit_price": "0,08",     //  <- culprit
  "extended_hours": true
}
```

Which is formating the `limit_price` using:
https://github.com/Petersoj/alpaca-java/blob/4e70b6004c92698e694241c24fbf0b7165e6fbd4/src/main/java/net/jacobpeterson/util/format/FormatUtil.java#L28-L30

This is using the coma (,) instead of the dot (.) that Alpaca is expecting.

Here is a minimalist main:
```java
public static void main(String[] args) {
	System.out.println(Locale.getDefault());
	System.out.println(FormatUtil.toCurrencyFormat((Double) 134.5));
}
```
```
en_US
134,50
```

I am pretty sure that this is a kind of locale problem.

**Comment by Petersoj** [comment] 2021-04-26 21:22
@Caceresenzo yes I believe you're correct. The `NumberFormat` instance doesn't specify the `EN_US` locale explicitly. I will fix this. Thank you!

**Comment by Caceresenzo** [comment] 2021-04-26 21:24
Glad to hear that!

I tested with a simple HTTP client, and if you do replace the coma (,) with the dot (.), everything work fine.

**Comment by Petersoj** [comment] 2021-04-26 22:54
Fixed in 019c617a0a2ed58c0b9e27a7933698e5b3b58f2e

**Closed as completed by Petersoj** 2021-04-26 22:54 UTC

**Comment by Caceresenzo** [comment] 2021-04-27 16:18
When will this be in master?

**Comment by Petersoj** [comment] 2021-04-27 19:28
@Caceresenzo I will make a patch release later today.

**Comment by Petersoj** [comment] 2021-04-27 20:19
@Caceresenzo [`7.1.1`](https://github.com/Petersoj/alpaca-java/releases/tag/7.1.1) is has been published. Should be accessible from Maven Central in an hour or so.

**Comment by Caceresenzo** [comment] 2021-04-27 20:21
@Petersoj many thanks!
